// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package models

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, description, workspace_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, workspace_id
`

type CreateAccountParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	WorkspaceID int64  `json:"workspace_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.Description, arg.WorkspaceID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkspaceID,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, description, workspace_id FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkspaceID,
	)
	return i, err
}

const listAccountsByWorkspace = `-- name: ListAccountsByWorkspace :many
SELECT id, name, description, workspace_id FROM accounts
WHERE workspace_id = $1
ORDER BY id
`

func (q *Queries) ListAccountsByWorkspace(ctx context.Context, workspaceID int64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2, description = $3
WHERE id = $1
RETURNING id, name, description, workspace_id
`

type UpdateAccountParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount, arg.ID, arg.Name, arg.Description)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WorkspaceID,
	)
	return i, err
}
