// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_roles.sql

package models

import (
	"context"
)

const bindAccountRole = `-- name: BindAccountRole :one
INSERT INTO account_roles (role_id, account_id)
VALUES ($1, $2)
RETURNING role_id, account_id
`

type BindAccountRoleParams struct {
	RoleID    int64 `json:"role_id"`
	AccountID int64 `json:"account_id"`
}

func (q *Queries) BindAccountRole(ctx context.Context, arg BindAccountRoleParams) (AccountRole, error) {
	row := q.db.QueryRowContext(ctx, bindAccountRole, arg.RoleID, arg.AccountID)
	var i AccountRole
	err := row.Scan(&i.RoleID, &i.AccountID)
	return i, err
}

const listAccountRoles = `-- name: ListAccountRoles :many
SELECT role_id, account_id FROM account_roles
ORDER BY role_id, account_id
`

func (q *Queries) ListAccountRoles(ctx context.Context) ([]AccountRole, error) {
	rows, err := q.db.QueryContext(ctx, listAccountRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountRole{}
	for rows.Next() {
		var i AccountRole
		if err := rows.Scan(&i.RoleID, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByRole = `-- name: ListAccountsByRole :many
SELECT a.id, a.name, a.description, a.workspace_id FROM accounts a
JOIN account_roles ar ON ar.account_id = a.id
WHERE ar.role_id = $1
ORDER BY a.id
`

func (q *Queries) ListAccountsByRole(ctx context.Context, roleID int64) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByAccount = `-- name: ListRolesByAccount :many
SELECT r.id, r.name, r.description, r.workspace_id FROM roles r
JOIN account_roles ar ON ar.role_id = r.id
WHERE ar.account_id = $1
ORDER BY r.id
`

func (q *Queries) ListRolesByAccount(ctx context.Context, accountID int64) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbindAccountRole = `-- name: UnbindAccountRole :exec
DELETE FROM account_roles
WHERE role_id = $1 AND account_id = $2
`

type UnbindAccountRoleParams struct {
	RoleID    int64 `json:"role_id"`
	AccountID int64 `json:"account_id"`
}

func (q *Queries) UnbindAccountRole(ctx context.Context, arg UnbindAccountRoleParams) error {
	_, err := q.db.ExecContext(ctx, unbindAccountRole, arg.RoleID, arg.AccountID)
	return err
}
