// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"time"
)

type Account struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	WorkspaceID int64  `json:"workspace_id"`
}

type AccountRole struct {
	RoleID    int64 `json:"role_id"`
	AccountID int64 `json:"account_id"`
}

type Role struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	WorkspaceID int64  `json:"workspace_id"`
}

type SchemaMigration struct {
	Version   int64     `json:"version"`
	AppliedAt time.Time `json:"applied_at"`
}

type User struct {
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type Workspace struct {
	ID        int32  `json:"id"`
	UserEmail string `json:"user_email"`
}
