// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"
)

type Querier interface {
	AddServiceAccountUsage(ctx context.Context, arg AddServiceAccountUsageParams) error
	CountUsers(ctx context.Context) (int64, error)
	CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error)
	CreateServiceAccountMeta(ctx context.Context, accountID int32) (ServiceAccountMetum, error)
	DeleteServiceAccount(ctx context.Context, id int32) error
	DeleteServiceAccountKV(ctx context.Context, id int32) error
	DeleteServiceAccountKVByAccount(ctx context.Context, accountID int32) error
	DeleteServiceAccountMeta(ctx context.Context, accountID int32) error
	GetServiceAccount(ctx context.Context, id int32) (ServiceAccount, error)
	GetServiceAccountMeta(ctx context.Context, accountID int32) (ServiceAccountMetum, error)
	ListServiceAccountKV(ctx context.Context, accountID int32) ([]ServiceAccountKv, error)
	ListUserServiceAccountKV(ctx context.Context, userEmail string) ([]ListUserServiceAccountKVRow, error)
	ListUserServiceAccounts(ctx context.Context, userEmail string) ([]ListUserServiceAccountsRow, error)
	SetServiceAccountKV(ctx context.Context, arg SetServiceAccountKVParams) (ServiceAccountKv, error)
	UpdateServiceAccount(ctx context.Context, arg UpdateServiceAccountParams) (ServiceAccount, error)
	UpdateServiceAccountMeta(ctx context.Context, arg UpdateServiceAccountMetaParams) (ServiceAccountMetum, error)
	UpsertUser(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
