// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_account_kv.sql

package models

import (
	"context"
)

const deleteServiceAccountKV = `-- name: DeleteServiceAccountKV :exec
DELETE FROM service_account_kv
WHERE id = $1
`

func (q *Queries) DeleteServiceAccountKV(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteServiceAccountKV, id)
	return err
}

const listServiceAccountKV = `-- name: ListServiceAccountKV :many
SELECT id, account_id, xkey, xvalue FROM service_account_kv
WHERE account_id = $1
ORDER BY xkey
`

func (q *Queries) ListServiceAccountKV(ctx context.Context, accountID int32) ([]ServiceAccountKv, error) {
	rows, err := q.db.QueryContext(ctx, listServiceAccountKV, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceAccountKv{}
	for rows.Next() {
		var i ServiceAccountKv
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Xkey,
			&i.Xvalue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServiceAccountKV = `-- name: SetServiceAccountKV :one
INSERT INTO service_account_kv (account_id, xkey, xvalue)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, xkey) DO UPDATE SET xvalue = EXCLUDED.xvalue
RETURNING id, account_id, xkey, xvalue
`

type SetServiceAccountKVParams struct {
	AccountID int32  `json:"account_id"`
	Xkey      string `json:"xkey"`
	Xvalue    string `json:"xvalue"`
}

func (q *Queries) SetServiceAccountKV(ctx context.Context, arg SetServiceAccountKVParams) (ServiceAccountKv, error) {
	row := q.db.QueryRowContext(ctx, setServiceAccountKV, arg.AccountID, arg.Xkey, arg.Xvalue)
	var i ServiceAccountKv
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Xkey,
		&i.Xvalue,
	)
	return i, err
}
