// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_accounts.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const createServiceAccount = `-- name: CreateServiceAccount :one
INSERT INTO service_accounts (name, description, active, user_email, ttl_seconds)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, active, user_email, created_at, ttl_seconds
`

type CreateServiceAccountParams struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Active      bool          `json:"active"`
	UserEmail   string        `json:"user_email"`
	TtlSeconds  sql.NullInt64 `json:"ttl_seconds"`
}

func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error) {
	row := q.db.QueryRowContext(ctx, createServiceAccount,
		arg.Name,
		arg.Description,
		arg.Active,
		arg.UserEmail,
		arg.TtlSeconds,
	)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.UserEmail,
		&i.CreatedAt,
		&i.TtlSeconds,
	)
	return i, err
}

const deleteServiceAccount = `-- name: DeleteServiceAccount :exec
DELETE FROM service_accounts
WHERE id = $1
`

func (q *Queries) DeleteServiceAccount(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteServiceAccount, id)
	return err
}

const getServiceAccount = `-- name: GetServiceAccount :one
SELECT id, name, description, active, user_email, created_at, ttl_seconds FROM service_accounts
WHERE id = $1
`

func (q *Queries) GetServiceAccount(ctx context.Context, id int32) (ServiceAccount, error) {
	row := q.db.QueryRowContext(ctx, getServiceAccount, id)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.UserEmail,
		&i.CreatedAt,
		&i.TtlSeconds,
	)
	return i, err
}

const listUserServiceAccounts = `-- name: ListUserServiceAccounts :many
SELECT id, name, description, active, user_email, created_at, ttl_seconds, account_id, last_used, usage
FROM service_accounts as sa JOIN service_account_meta as sam ON sa.id = sam.account_id
WHERE user_email = $1
ORDER BY id
`

type ListUserServiceAccountsRow struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Active      bool          `json:"active"`
	UserEmail   string        `json:"user_email"`
	CreatedAt   time.Time     `json:"created_at"`
	TtlSeconds  sql.NullInt64 `json:"ttl_seconds"`
	AccountID   int32         `json:"account_id"`
	LastUsed    sql.NullTime  `json:"last_used"`
	Usage       int64         `json:"usage"`
}

func (q *Queries) ListUserServiceAccounts(ctx context.Context, userEmail string) ([]ListUserServiceAccountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserServiceAccounts, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserServiceAccountsRow{}
	for rows.Next() {
		var i ListUserServiceAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.UserEmail,
			&i.CreatedAt,
			&i.TtlSeconds,
			&i.AccountID,
			&i.LastUsed,
			&i.Usage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceAccount = `-- name: UpdateServiceAccount :one
UPDATE service_accounts
SET name = $2, description = $3, active = $4, ttl_seconds = $5
WHERE id = $1
RETURNING id, name, description, active, user_email, created_at, ttl_seconds
`

type UpdateServiceAccountParams struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Active      bool          `json:"active"`
	TtlSeconds  sql.NullInt64 `json:"ttl_seconds"`
}

func (q *Queries) UpdateServiceAccount(ctx context.Context, arg UpdateServiceAccountParams) (ServiceAccount, error) {
	row := q.db.QueryRowContext(ctx, updateServiceAccount,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Active,
		arg.TtlSeconds,
	)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.UserEmail,
		&i.CreatedAt,
		&i.TtlSeconds,
	)
	return i, err
}
