// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package models

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING email, created_at
`

func (q *Queries) UpsertUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, email)
	var i User
	err := row.Scan(&i.Email, &i.CreatedAt)
	return i, err
}
