// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package models

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (user_email)
VALUES ($1)
RETURNING id, user_email
`

func (q *Queries) CreateWorkspace(ctx context.Context, userEmail string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, userEmail)
	var i Workspace
	err := row.Scan(&i.ID, &i.UserEmail)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces
WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, user_email FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id int32) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(&i.ID, &i.UserEmail)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, user_email FROM workspaces
ORDER BY id
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(&i.ID, &i.UserEmail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT id, user_email FROM workspaces
WHERE user_email = $1
ORDER BY id
`

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userEmail string) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByUser, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(&i.ID, &i.UserEmail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET user_email = $2
WHERE id = $1
RETURNING id, user_email
`

type UpdateWorkspaceParams struct {
	ID        int32  `json:"id"`
	UserEmail string `json:"user_email"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspace, arg.ID, arg.UserEmail)
	var i Workspace
	err := row.Scan(&i.ID, &i.UserEmail)
	return i, err
}
